### ISSUE TITLE
Gocryptfs executable could not be found

### ISSUE THREAD

**Issue by anewuser** [mhogomchungu/cryfs-gui#6]
I've installed your application by downloading the `.deb` package from your personal OpenSuse repository.

The [official gocryptfs page](https://nuetzlich.net/gocryptfs/quickstart/) advises to put their binary in `~/bin/`, but cryfs-gui looks for it in `/bin/`.  Your "could not be found" warning should tell users the proper location to place the gocryptfs binary.

**Comment by mhogomchungu** [comment]
A list of searched directories is here[1]. These are "standard" paths for executables and i think its reasonable to expect users to know at least one of them.

I think "~/bin" is a bad path for backends when used by frontends that passes sensitive data to backends because any person who has access to your user account(an adversary could ask to check their emails quickly using your computer) can easily substitute the real executable with a fake one that steals your password before calling the real executable hiding their existence..

[1] https://github.com/mhogomchungu/cryfs-gui/blob/0240d0ef73d7f82787d1830977d9fde37c364c47/src/utility.cpp#L240

**Comment by mhogomchungu** [comment]
I have added an entry in the FAQ[1] to mention the list of searched directories for backend executables.

[1]https://github.com/mhogomchungu/cryfs-gui/wiki/Frequently-Asked-Questions#50-what-directories-does-cryfs-gui-check-for-its-backend-executables
